### ISSUE TITLE
Little too forceful: toggle forcing?

### ISSUE THREAD

**Issue by tedyoung** [treytrahin/compelshortcuts#1]
There are times where shortcut keys either don't work, or aren't shown, so I'm stuck.

Example: during a file diff/merge, there are toolbar buttons that don't have obvious shortcuts (or at least they're not being shown, so I'm stuck).

Would be great if there was a quick way to toggle the force on/off so I don't have to disable the plugin.

**Comment by treytrahin** [comment]
Initially I thought it would be nice if it was hard to disable, _really_ forcing you to use the hotkeys, but I agree there are situations where it would be nice to turn it off. Especially if it's not even showing a shortcut to use instead!

I just pushed an update that adds a toggle to the menu bar. Hope that solves things! I'll take a look at what's going on with the diff/merge window hotkeys as well.

**Comment by tedyoung** [comment]
That's perfect. I have to say it's been really helpful forcing me to learn the Mac shortcuts (coming from Windows/Linux), so I'll try not to abuse the toggle switch. :)

The shortcut that I had a problem with in the diff/merge window was moving to the next/previous file. Supposedly it's ^<- (control+arrow), but that wasn't working for me (it would just move the cursor between the two panes of the window).
