### ISSUE TITLE
No build information

### ISSUE THREAD

**Issue by tedyoung** [treytrahin/compelshortcuts#3]
I don't see any Maven or Gradle build files. How are you building the JAR (or ZIP) file?

**Comment by treytrahin** [comment]
When you open the project in IntelliJ, there's an extra menu item under `Build` that says `Prepare Plugin Module 'force-shortcuts' For Deployment`. I've just used this, as the project isn't bringing in any dependencies beyond what IntelliJ has access to already.

**Comment by treytrahin** [comment]
Added build documentation to the README in this commit `f06fc09265e8232fd58d2e24a29a3b5a38617633`
