### ISSUE TITLE
This should also support webstorm and other jetbrains products

### ISSUE THREAD

**Issue by GuyMograbi** [treytrahin/compelshortcuts#4]
This is an awesome plugin! I love it. 

My friends cannot use it though because it is only for intellij. 

Is it hard to add support to other jetbrain products? like webstorm?

**Comment by treytrahin** [comment]
I've been meaning to get around to this, after initially being unsure how painful it would be. Turns out it was no big deal, so I pushed an update that should allow it in all JetBrains products. It's currently pending approval by JetBrains, but it should be available everywhere soon!
